name: supla-pushover-develop

on: 
  push:
    branches: 
    - supla-pushover-develop
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: supla-pushover-develop
    - name: make all
      run: cd supla-console-client/Release && make all
